-- this file was automatically generated by CompanionData.py

local Doolittle = LibStub("AceAddon-3.0"):GetAddon("Doolittle")

Doolittle.CRITTER = {
	pools = {
		-- if other pet reagents are ever added, this will be replaced
		-- with a proper generator like the one used for mounts
		i17202 = { -- Snowball
			26533, -- Father Winter's Helper
			26045, -- Tiny Snowman
			26529, -- Winter Reindeer
			26541, -- Winter's Little Helper
		},
	},
}

Doolittle.MOUNT = {
	pools = {
		aq40 = {
			25953, -- Blue Qiraji Battle Tank
			26056, -- Green Qiraji Battle Tank
			26054, -- Red Qiraji Battle Tank
			26055, -- Yellow Qiraji Battle Tank
		},
		flying = Pool{
			71342, -- Big Love Rocket
			32244, -- Blue Wind Rider
			75614, -- Celestial Steed
			32239, -- Ebon Gryphon
			61451, -- Flying Carpet
			44153, -- Flying Machine
			32235, -- Golden Gryphon
			32245, -- Green Wind Rider
			48025, -- Headless Horseman's Mount
			72286, -- Invincible
			32240, -- Snowy Gryphon
			32243, -- Tawny Wind Rider
			54729, -- Winged Steed of the Ebon Blade
			46197, -- X-51 Nether-Rocket
			60025, -- Albino Drake
			63844, -- Argent Hippogryph
			61230, -- Armored Blue Wind Rider
			61229, -- Armored Snowy Gryphon
			59567, -- Azure Drake
			41514, -- Azure Netherwing Drake
			71342, -- Big Love Rocket
			59650, -- Black Drake
			61996, -- Blue Dragonhawk
			59568, -- Blue Drake
			59996, -- Blue Proto-Drake
			39803, -- Blue Riding Nether Ray
			59569, -- Bronze Drake
			75614, -- Celestial Steed
			43927, -- Cenarion War Hippogryph
			41515, -- Cobalt Netherwing Drake
			61294, -- Green Proto-Drake
			39798, -- Green Riding Nether Ray
			48025, -- Headless Horseman's Mount
			72286, -- Invincible
			61309, -- Magnificent Flying Carpet
			41513, -- Onyx Netherwing Drake
			41516, -- Purple Netherwing Drake
			39801, -- Purple Riding Nether Ray
			61997, -- Red Dragonhawk
			59570, -- Red Drake
			59961, -- Red Proto-Drake
			39800, -- Red Riding Nether Ray
			66087, -- Silver Covenant Hippogryph
			39802, -- Silver Riding Nether Ray
			66088, -- Sunreaver Dragonhawk
			32242, -- Swift Blue Gryphon
			32290, -- Swift Green Gryphon
			32295, -- Swift Green Wind Rider
			32292, -- Swift Purple Gryphon
			32297, -- Swift Purple Wind Rider
			32289, -- Swift Red Gryphon
			32246, -- Swift Red Wind Rider
			32296, -- Swift Yellow Wind Rider
			60002, -- Time-Lost Proto-Drake
			44151, -- Turbo-Charged Flying Machine
			59571, -- Twilight Drake
			41517, -- Veridian Netherwing Drake
			41518, -- Violet Netherwing Drake
			54729, -- Winged Steed of the Ebon Blade
			46199, -- X-51 Nether-Rocket X-TREME
			40192, -- Ashes of Al'ar
			59976, -- Black Proto-Drake
			72808, -- Bloodbathed Frostbrood Vanquisher
			58615, -- Brutal Nether Drake
			75614, -- Celestial Steed
			64927, -- Deadly Gladiator's Frost Wyrm
			65439, -- Furious Gladiator's Frost Wyrm
			72807, -- Icebound Frostbrood Vanquisher
			63956, -- Ironbound Proto-Drake
			44744, -- Merciless Nether Drake
			63796, -- Mimiron's Head
			69395, -- Onyxian Drake
			32345, -- Peep the Phoenix Mount
			60021, -- Plagued Proto-Drake
			67336, -- Relentless Gladiator's Frost Wyrm
			63963, -- Rusted Proto-Drake
			37015, -- Swift Nether Drake
			49193, -- Vengeful Nether Drake
			60024, -- Violet Proto-Drake
			71810, -- Wrathful Gladiator's Frost Wyrm
		},
		ground = Pool{
			30174, -- Riding Turtle
			66907, -- Argent Warhorse
			58983, -- Big Blizzard Bear
			71342, -- Big Love Rocket
			35022, -- Black Hawkstrider
			64977, -- Black Skeletal Horse
			  470, -- Black Stallion
			64658, -- Black Wolf
			35020, -- Blue Hawkstrider
			10969, -- Blue Mechanostrider
			17463, -- Blue Skeletal Horse
			50869, -- Brewfest Kodo
			43899, -- Brewfest Ram
			34406, -- Brown Elekk
			  458, -- Brown Horse
			18990, -- Brown Kodo
			 6899, -- Brown Ram
			17464, -- Brown Skeletal Horse
			 6654, -- Brown Wolf
			 6648, -- Chestnut Mare
			 6653, -- Dire Wolf
			 8395, -- Emerald Raptor
			 5784, -- Felsteed
			35710, -- Gray Elekk
			18989, -- Gray Kodo
			 6777, -- Gray Ram
			17453, -- Green Mechanostrider
			48025, -- Headless Horseman's Mount
			72286, -- Invincible
			65917, -- Magic Rooster
			  472, -- Pinto
			35711, -- Purple Elekk
			35018, -- Purple Hawkstrider
			34795, -- Red Hawkstrider
			10873, -- Red Mechanostrider
			17462, -- Red Skeletal Horse
			64731, -- Sea Turtle
			42776, -- Spectral Tiger
			10789, -- Spotted Frostsaber
			66847, -- Striped Dawnsaber
			 8394, -- Striped Frostsaber
			10793, -- Striped Nightsaber
			34769, -- Summon Warhorse
			  580, -- Timber Wolf
			10796, -- Turquoise Raptor
			17454, -- Unpainted Mechanostrider
			10799, -- Violet Raptor
			13819, -- Warhorse
			64657, -- White Kodo
			 6898, -- White Ram
			48778, -- Acherus Deathcharger
			43688, -- Amani War Bear
			16056, -- Ancient Frostsaber
			66906, -- Argent Charger
			67466, -- Argent Warhorse
			60114, -- Armored Brown Bear
			60116, -- Armored Brown Bear
			51412, -- Big Battle Bear
			58983, -- Big Blizzard Bear
			71342, -- Big Love Rocket
			22719, -- Black Battlestrider
			16055, -- Black Nightsaber
			26656, -- Black Qiraji Battle Tank
			17461, -- Black Ram
			60118, -- Black War Bear
			60119, -- Black War Bear
			48027, -- Black War Elekk
			22718, -- Black War Kodo
			59785, -- Black War Mammoth
			59788, -- Black War Mammoth
			22720, -- Black War Ram
			22721, -- Black War Raptor
			22717, -- Black War Steed
			22723, -- Black War Tiger
			22724, -- Black War Wolf
			25953, -- Blue Qiraji Battle Tank
			64656, -- Blue Skeletal Warhorse
			23214, -- Charger
			39315, -- Cobalt Riding Talbuk
			34896, -- Cobalt War Talbuk
			68188, -- Crusader's Black Warhorse
			68187, -- Crusader's White Warhorse
			39316, -- Dark Riding Talbuk
			34790, -- Dark War Talbuk
			63635, -- Darkspear Raptor
			63637, -- Darnassian Nightsaber
			23161, -- Dreadsteed
			63639, -- Exodar Elekk
			36702, -- Fiery Warhorse
			63643, -- Forsaken Warhorse
			17460, -- Frost Ram
			23509, -- Frostwolf Howler
			63638, -- Gnomeregan Mechanostrider
			61465, -- Grand Black War Mammoth
			61467, -- Grand Black War Mammoth
			61469, -- Grand Ice Mammoth
			61470, -- Grand Ice Mammoth
			35713, -- Great Blue Elekk
			49379, -- Great Brewfest Kodo
			23249, -- Great Brown Kodo
			65641, -- Great Golden Kodo
			23248, -- Great Gray Kodo
			35712, -- Great Green Elekk
			35714, -- Great Purple Elekk
			65637, -- Great Red Elekk
			23247, -- Great White Kodo
			18991, -- Green Kodo
			26056, -- Green Qiraji Battle Tank
			17465, -- Green Skeletal Warhorse
			48025, -- Headless Horseman's Mount
			59797, -- Ice Mammoth
			59799, -- Ice Mammoth
			17459, -- Icy Blue Mechanostrider Mod A
			72286, -- Invincible
			63636, -- Ironforge Ram
			17450, -- Ivory Raptor
			65917, -- Magic Rooster
			55531, -- Mechano-hog
			60424, -- Mekgineer's Chopper
			16084, -- Mottled Red Raptor
			66846, -- Ochre Skeletal Warhorse
			63640, -- Orgrimmar Wolf
			16082, -- Palomino
			23246, -- Purple Skeletal Warhorse
			66090, -- Quel'dorei Steed
			41252, -- Raven Lord
			26054, -- Red Qiraji Battle Tank
			22722, -- Red Skeletal Warhorse
			16080, -- Red Wolf
			17481, -- Rivendare's Deathcharger
			39317, -- Silver Riding Talbuk
			34898, -- Silver War Talbuk
			63642, -- Silvermoon Hawkstrider
			23510, -- Stormpike Battle Charger
			63232, -- Stormwind Steed
			34767, -- Summon Charger
			66091, -- Sunreaver Hawkstrider
			68057, -- Swift Alliance Steed
			23241, -- Swift Blue Raptor
			43900, -- Swift Brewfest Ram
			23238, -- Swift Brown Ram
			23229, -- Swift Brown Steed
			23250, -- Swift Brown Wolf
			65646, -- Swift Burgundy Wolf
			23221, -- Swift Frostsaber
			23239, -- Swift Gray Ram
			65640, -- Swift Gray Steed
			23252, -- Swift Gray Wolf
			35025, -- Swift Green Hawkstrider
			23225, -- Swift Green Mechanostrider
			68056, -- Swift Horde Wolf
			23219, -- Swift Mistsaber
			65638, -- Swift Moonsaber
			23242, -- Swift Olive Raptor
			23243, -- Swift Orange Raptor
			23227, -- Swift Palomino
			33660, -- Swift Pink Hawkstrider
			35027, -- Swift Purple Hawkstrider
			65644, -- Swift Purple Raptor
			24242, -- Swift Razzashi Raptor
			65639, -- Swift Red Hawkstrider
			42777, -- Swift Spectral Tiger
			23338, -- Swift Stormsaber
			23251, -- Swift Timber Wolf
			65643, -- Swift Violet Ram
			35028, -- Swift Warstrider
			46628, -- Swift White Hawkstrider
			23223, -- Swift White Mechanostrider
			23240, -- Swift White Ram
			23228, -- Swift White Steed
			23222, -- Swift Yellow Mechanostrider
			49322, -- Swift Zhevra
			24252, -- Swift Zulian Tiger
			39318, -- Tan Riding Talbuk
			34899, -- Tan War Talbuk
			18992, -- Teal Kodo
			63641, -- Thunder Bluff Kodo
			61425, -- Traveler's Tundra Mammoth
			61447, -- Traveler's Tundra Mammoth
			65642, -- Turbostrider
			64659, -- Venomhide Ravasaur
			15779, -- White Mechanostrider Mod B
			54753, -- White Polar Bear
			39319, -- White Riding Talbuk
			65645, -- White Skeletal Warhorse
			16083, -- White Stallion
			34897, -- White War Talbuk
			16081, -- Winter Wolf
			17229, -- Winterspring Frostsaber
			59791, -- Wooly Mammoth
			59793, -- Wooly Mammoth
			26055, -- Yellow Qiraji Battle Tank
		},
		swimming = Pool{
			64731, -- Sea Turtle
			75207, -- Abyssal Seahorse
		},
	},
}

-- Generated on Tue, 12 Jan 2010 17:09:09Z in 38.944 seconds
