-- this file was automatically generated by wowhead.php

local Doolittle = LibStub("AceAddon-3.0"):GetAddon("Doolittle")

Doolittle.wowhead = {
	mounts = {
		data = {
			[60025] = { -- Albino Drake
				flying = 280,
			},
			[43688] = { -- Amani War Bear
				ground = 100,
			},
			[16056] = { -- Ancient Frostsaber
				ground = 100,
			},
			[63844] = { -- Argent Hippogryph
				flying = 280,
			},
			[61230] = { -- Armored Blue Wind Rider
				flying = 280,
			},
			[60114] = { -- Armored Brown Bear
				ground = 100,
			},
			[60116] = { -- Armored Brown Bear
				ground = 100,
			},
			[61229] = { -- Armored Snowy Gryphon
				flying = 280,
			},
			[40192] = { -- Ashes of Al'ar
				flying = 310,
			},
			[59567] = { -- Azure Drake
				flying = 280,
			},
			[41514] = { -- Azure Netherwing Drake
				flying = 280,
			},
			[51412] = { -- Big Battle Bear
				ground = 100,
			},
			[58983] = { -- Big Blizzard Bear
				ground = -1,
			},
			[22719] = { -- Black Battlestrider
				ground = 100,
			},
			[62048] = { -- Black Dragonhawk Mount
				flying = 280,
			},
			[59650] = { -- Black Drake
				flying = 280,
			},
			[35022] = { -- Black Hawkstrider
				ground = 60,
			},
			[16055] = { -- Black Nightsaber
				ground = 100,
			},
			[59572] = { -- Black Polar Bear
				ground = 100,
			},
			[59976] = { -- Black Proto-Drake
				flying = 310,
			},
			[26656] = { -- Black Qiraji Battle Tank
				ground = 100,
			},
			[6896] = { -- Black Ram
				ground = 60,
			},
			[17461] = { -- Black Ram
				ground = 100,
			},
			[64977] = { -- Black Skeletal Horse
				ground = 60,
			},
			[470] = { -- Black Stallion
				ground = 60,
			},
			[60118] = { -- Black War Bear
				ground = 100,
			},
			[60119] = { -- Black War Bear
				ground = 100,
			},
			[48027] = { -- Black War Elekk
				ground = 100,
			},
			[22718] = { -- Black War Kodo
				ground = 100,
			},
			[59785] = { -- Black War Mammoth
				ground = 100,
			},
			[59788] = { -- Black War Mammoth
				ground = 100,
			},
			[22720] = { -- Black War Ram
				ground = 100,
			},
			[22721] = { -- Black War Raptor
				ground = 100,
			},
			[22717] = { -- Black War Steed
				ground = 100,
			},
			[22723] = { -- Black War Tiger
				ground = 100,
			},
			[22724] = { -- Black War Wolf
				ground = 100,
			},
			[578] = { -- Black Wolf
				ground = 60,
			},
			[64658] = { -- Black Wolf
				ground = 60,
			},
			[61996] = { -- Blue Dragonhawk
				flying = 280,
			},
			[59568] = { -- Blue Drake
				flying = 280,
			},
			[35020] = { -- Blue Hawkstrider
				ground = 60,
			},
			[10969] = { -- Blue Mechanostrider
				ground = 60,
			},
			[33630] = { -- Blue Mechanostrider
				ground = 60,
			},
			[59996] = { -- Blue Proto-Drake
				flying = 280,
			},
			[25953] = { -- Blue Qiraji Battle Tank
				ground = 100,
			},
			[6897] = { -- Blue Ram
				ground = 60,
			},
			[39803] = { -- Blue Riding Nether Ray
				flying = 280,
			},
			[17463] = { -- Blue Skeletal Horse
				ground = 60,
			},
			[64656] = { -- Blue Skeletal Warhorse
				ground = 100,
			},
			[32244] = { -- Blue Wind Rider
				flying = 60,
			},
			[50869] = { -- Brewfest Kodo
				ground = 60,
			},
			[43899] = { -- Brewfest Ram
				ground = 60,
			},
			[50870] = { -- Brewfest Ram
				ground = 60,
			},
			[49378] = { -- Brewfest Riding Kodo
				ground = 60,
			},
			[59569] = { -- Bronze Drake
				flying = 280,
			},
			[34406] = { -- Brown Elekk
				ground = 60,
			},
			[458] = { -- Brown Horse
				ground = 60,
			},
			[18990] = { -- Brown Kodo
				ground = 60,
			},
			[59573] = { -- Brown Polar Bear
				ground = 100,
			},
			[6899] = { -- Brown Ram
				ground = 60,
			},
			[17464] = { -- Brown Skeletal Horse
				ground = 60,
			},
			[6654] = { -- Brown Wolf
				ground = 60,
			},
			[58615] = { -- Brutal Nether Drake
				flying = 310,
			},
			[43927] = { -- Cenarion War Hippogryph
				flying = 280,
			},
			[6648] = { -- Chestnut Mare
				ground = 60,
			},
			[41515] = { -- Cobalt Netherwing Drake
				flying = 280,
			},
			[39315] = { -- Cobalt Riding Talbuk
				ground = 100,
			},
			[34896] = { -- Cobalt War Talbuk
				ground = 100,
			},
			[39316] = { -- Dark Riding Talbuk
				ground = 100,
			},
			[34790] = { -- Dark War Talbuk
				ground = 100,
			},
			[64927] = { -- Deadly Gladiator's Frostwyrm
				flying = 310,
			},
			[6653] = { -- Dire Wolf
				ground = 60,
			},
			[32239] = { -- Ebon Gryphon
				flying = 60,
			},
			[8395] = { -- Emerald Raptor
				ground = 60,
			},
			[36702] = { -- Fiery Warhorse
				ground = 100,
			},
			[17458] = { -- Fluorescent Green Mechanostrider
				ground = 60,
			},
			[61451] = { -- Flying Carpet
				flying = 60,
			},
			[44153] = { -- Flying Machine
				flying = 60,
			},
			[63643] = { -- Forsaken Warhorse
				ground = 100,
			},
			[17460] = { -- Frost Ram
				ground = 100,
			},
			[43810] = { -- Frost Wyrm
				flying = 280,
			},
			[23509] = { -- Frostwolf Howler
				ground = 100,
			},
			[51960] = { -- Frostwyrm Mount
				flying = 280,
			},
			[32235] = { -- Golden Gryphon
				flying = 60,
			},
			[16060] = { -- Golden Sabercat
				ground = 60,
			},
			[59810] = { -- Grand Black War Mammoth
				ground = 100,
			},
			[59811] = { -- Grand Black War Mammoth
				ground = 100,
			},
			[61465] = { -- Grand Black War Mammoth
				ground = 100,
			},
			[61467] = { -- Grand Black War Mammoth
				ground = 100,
			},
			[60136] = { -- Grand Caravan Mammoth
				ground = 100,
			},
			[60140] = { -- Grand Caravan Mammoth
				ground = 100,
			},
			[59802] = { -- Grand Ice Mammoth
				ground = 100,
			},
			[59804] = { -- Grand Ice Mammoth
				ground = 100,
			},
			[61469] = { -- Grand Ice Mammoth
				ground = 100,
			},
			[61470] = { -- Grand Ice Mammoth
				ground = 100,
			},
			[35710] = { -- Gray Elekk
				ground = 60,
			},
			[18989] = { -- Gray Kodo
				ground = 60,
			},
			[6777] = { -- Gray Ram
				ground = 60,
			},
			[459] = { -- Gray Wolf
				ground = 60,
			},
			[63639] = { -- Great Azuremyst Elekk
				ground = 100,
			},
			[35713] = { -- Great Blue Elekk
				ground = 100,
			},
			[49379] = { -- Great Brewfest Kodo
				ground = 100,
			},
			[23249] = { -- Great Brown Kodo
				ground = 100,
			},
			[34407] = { -- Great Elite Elekk
				ground = 100,
			},
			[23248] = { -- Great Gray Kodo
				ground = 100,
			},
			[35712] = { -- Great Green Elekk
				ground = 100,
			},
			[63641] = { -- Great Mulgore Kodo
				ground = 100,
			},
			[35714] = { -- Great Purple Elekk
				ground = 100,
			},
			[23247] = { -- Great White Kodo
				ground = 100,
			},
			[18991] = { -- Green Kodo
				ground = 100,
			},
			[15780] = { -- Green Mechanostrider
				ground = 60,
			},
			[17453] = { -- Green Mechanostrider
				ground = 60,
			},
			[61294] = { -- Green Proto-Drake
				flying = 280,
			},
			[26056] = { -- Green Qiraji Battle Tank
				ground = 100,
			},
			[39798] = { -- Green Riding Nether Ray
				flying = 280,
			},
			[17465] = { -- Green Skeletal Warhorse
				ground = 100,
			},
			[32245] = { -- Green Wind Rider
				flying = 60,
			},
			[48025] = { -- Headless Horseman's Mount
				flying = -1,
				ground = -1,
			},
			[59797] = { -- Ice Mammoth
				ground = 100,
			},
			[59799] = { -- Ice Mammoth
				ground = 100,
			},
			[17459] = { -- Icy Blue Mechanostrider Mod A
				ground = 100,
			},
			[63956] = { -- Ironbound Proto-Drake
				flying = 310,
			},
			[10795] = { -- Ivory Raptor
				ground = 60,
			},
			[17450] = { -- Ivory Raptor
				ground = 100,
			},
			[61309] = { -- Magnificent Flying Carpet
				flying = 280,
			},
			[55531] = { -- Mechano-hog
				ground = 100,
			},
			[60424] = { -- Mekgineer's Chopper
				ground = 100,
			},
			[44317] = { -- Merciless Nether Drake
				flying = 310,
			},
			[44744] = { -- Merciless Nether Drake
				flying = 310,
			},
			[63796] = { -- Mimiron's Head
				flying = 310,
			},
			[16084] = { -- Mottled Red Raptor
				ground = 100,
			},
			[29059] = { -- Naxxramas Deathcharger
				ground = 100,
			},
			[3363] = { -- Nether Drake
				flying = 310,
			},
			[10798] = { -- Obsidian Raptor
				ground = 60,
			},
			[41513] = { -- Onyx Netherwing Drake
				flying = 280,
			},
			[471] = { -- Palamino
				ground = 60,
			},
			[16082] = { -- Palomino
				ground = 100,
			},
			[32345] = { -- Peep the Phoenix Mount
				flying = 310,
			},
			[472] = { -- Pinto
				ground = 60,
			},
			[60021] = { -- Plagued Proto-Drake
				flying = 310,
			},
			[16058] = { -- Primal Leopard
				ground = 60,
			},
			[35711] = { -- Purple Elekk
				ground = 60,
			},
			[35018] = { -- Purple Hawkstrider
				ground = 60,
			},
			[17455] = { -- Purple Mechanostrider
				ground = 60,
			},
			[41516] = { -- Purple Netherwing Drake
				flying = 280,
			},
			[39801] = { -- Purple Riding Nether Ray
				flying = 280,
			},
			[23246] = { -- Purple Skeletal Warhorse
				ground = 100,
			},
			[41252] = { -- Raven Lord
				ground = 100,
			},
			[17456] = { -- Red and Blue Mechanostrider
				ground = 60,
			},
			[61997] = { -- Red Dragonhawk
				flying = 280,
			},
			[59570] = { -- Red Drake
				flying = 280,
			},
			[34795] = { -- Red Hawkstrider
				ground = 60,
			},
			[10873] = { -- Red Mechanostrider
				ground = 60,
			},
			[59961] = { -- Red Proto-Drake
				flying = 280,
			},
			[26054] = { -- Red Qiraji Battle Tank
				ground = 100,
			},
			[39800] = { -- Red Riding Nether Ray
				flying = 280,
			},
			[17462] = { -- Red Skeletal Horse
				ground = 60,
			},
			[22722] = { -- Red Skeletal Warhorse
				ground = 100,
			},
			[579] = { -- Red Wolf
				ground = 100,
			},
			[16080] = { -- Red Wolf
				ground = 100,
			},
			[18363] = { -- Riding Kodo
				ground = 60,
			},
			[30174] = { -- Riding Turtle
				ground = 0,
			},
			[17481] = { -- Rivendare's Deathcharger
				ground = 100,
			},
			[63963] = { -- Rusted Proto-Drake
				flying = 310,
			},
			[64731] = { -- Sea Turtle
				swimming = 60,
			},
			[39802] = { -- Silver Riding Nether Ray
				flying = 280,
			},
			[39317] = { -- Silver Riding Talbuk
				ground = 100,
			},
			[34898] = { -- Silver War Talbuk
				ground = 100,
			},
			[8980] = { -- Skeletal Horse
				ground = 60,
			},
			[32240] = { -- Snowy Gryphon
				flying = 60,
			},
			[42776] = { -- Spectral Tiger
				ground = 60,
			},
			[10789] = { -- Spotted Frostsaber
				ground = 60,
			},
			[15781] = { -- Steel Mechanostrider
				ground = 60,
			},
			[23510] = { -- Stormpike Battle Charger
				ground = 100,
			},
			[8394] = { -- Striped Frostsaber
				ground = 60,
			},
			[10793] = { -- Striped Nightsaber
				ground = 60,
			},
			[32242] = { -- Swift Blue Gryphon
				flying = 280,
			},
			[23241] = { -- Swift Blue Raptor
				ground = 100,
			},
			[43900] = { -- Swift Brewfest Ram
				ground = 100,
			},
			[23238] = { -- Swift Brown Ram
				ground = 100,
			},
			[23229] = { -- Swift Brown Steed
				ground = 100,
			},
			[23250] = { -- Swift Brown Wolf
				ground = 100,
			},
			[63635] = { -- Swift Darkspear Raptor
				ground = 100,
			},
			[63637] = { -- Swift Darnassian Mistsaber
				ground = 100,
			},
			[23220] = { -- Swift Dawnsaber
				ground = 100,
			},
			[63232] = { -- Swift Elwynn Steed
				ground = 100,
			},
			[23221] = { -- Swift Frostsaber
				ground = 100,
			},
			[23239] = { -- Swift Gray Ram
				ground = 100,
			},
			[23252] = { -- Swift Gray Wolf
				ground = 100,
			},
			[32290] = { -- Swift Green Gryphon
				flying = 280,
			},
			[35025] = { -- Swift Green Hawkstrider
				ground = 100,
			},
			[23225] = { -- Swift Green Mechanostrider
				ground = 100,
			},
			[32295] = { -- Swift Green Wind Rider
				flying = 280,
			},
			[63636] = { -- Swift Ironforge Ram
				ground = 100,
			},
			[23219] = { -- Swift Mistsaber
				ground = 100,
			},
			[61442] = { -- Swift Mooncloth Carpet
				flying = 280,
			},
			[37015] = { -- Swift Nether Drake
				flying = 310,
			},
			[23242] = { -- Swift Olive Raptor
				ground = 100,
			},
			[23243] = { -- Swift Orange Raptor
				ground = 100,
			},
			[63640] = { -- Swift Orgrimmar Wolf
				ground = 100,
			},
			[23227] = { -- Swift Palomino
				ground = 100,
			},
			[33660] = { -- Swift Pink Hawkstrider
				ground = 100,
			},
			[32292] = { -- Swift Purple Gryphon
				flying = 280,
			},
			[35027] = { -- Swift Purple Hawkstrider
				ground = 100,
			},
			[32297] = { -- Swift Purple Wind Rider
				flying = 280,
			},
			[24242] = { -- Swift Razzashi Raptor
				ground = 100,
			},
			[32289] = { -- Swift Red Gryphon
				flying = 280,
			},
			[32246] = { -- Swift Red Wind Rider
				flying = 280,
			},
			[61444] = { -- Swift Shadoweave Carpet
				flying = 280,
			},
			[63642] = { -- Swift Silvermoon Hawkstrider
				ground = 100,
			},
			[42777] = { -- Swift Spectral Tiger
				ground = 100,
			},
			[61446] = { -- Swift Spellfire Carpet
				flying = 280,
			},
			[23338] = { -- Swift Stormsaber
				ground = 100,
			},
			[23251] = { -- Swift Timber Wolf
				ground = 100,
			},
			[47037] = { -- Swift War  Elekk
				ground = 100,
			},
			[35028] = { -- Swift Warstrider
				ground = 100,
			},
			[46628] = { -- Swift White Hawkstrider
				ground = 100,
			},
			[23223] = { -- Swift White Mechanostrider
				ground = 100,
			},
			[23240] = { -- Swift White Ram
				ground = 100,
			},
			[23228] = { -- Swift White Steed
				ground = 100,
			},
			[23222] = { -- Swift Yellow Mechanostrider
				ground = 100,
			},
			[32296] = { -- Swift Yellow Wind Rider
				flying = 280,
			},
			[48954] = { -- Swift Zhevra
				ground = 100,
			},
			[49322] = { -- Swift Zhevra
				ground = 100,
			},
			[24252] = { -- Swift Zulian Tiger
				ground = 100,
			},
			[39318] = { -- Tan Riding Talbuk
				ground = 100,
			},
			[34899] = { -- Tan War Talbuk
				ground = 100,
			},
			[16059] = { -- Tawny Sabercat
				ground = 60,
			},
			[32243] = { -- Tawny Wind Rider
				flying = 60,
			},
			[18992] = { -- Teal Kodo
				ground = 100,
			},
			[580] = { -- Timber Wolf
				ground = 60,
			},
			[60002] = { -- Time-Lost Proto-Drake
				flying = 280,
			},
			[61425] = { -- Traveler's Tundra Mammoth
				ground = 100,
			},
			[61447] = { -- Traveler's Tundra Mammoth
				ground = 100,
			},
			[44151] = { -- Turbo-Charged Flying Machine
				flying = 280,
			},
			[63638] = { -- Turbostrider
				ground = 100,
			},
			[10796] = { -- Turquoise Raptor
				ground = 60,
			},
			[59571] = { -- Twilight Drake
				flying = 280,
			},
			[17454] = { -- Unpainted Mechanostrider
				ground = 60,
			},
			[49193] = { -- Vengeful Nether Drake
				flying = 310,
			},
			[64659] = { -- Venomhide Ravasaur
				ground = 100,
			},
			[41517] = { -- Veridian Netherwing Drake
				flying = 280,
			},
			[41518] = { -- Violet Netherwing Drake
				flying = 280,
			},
			[60024] = { -- Violet Proto-Drake
				flying = 310,
			},
			[10799] = { -- Violet Raptor
				ground = 60,
			},
			[64657] = { -- White Kodo
				ground = 60,
			},
			[15779] = { -- White Mechanostrider Mod B
				ground = 100,
			},
			[54753] = { -- White Polar Bear Mount
				ground = 100,
			},
			[6898] = { -- White Ram
				ground = 60,
			},
			[39319] = { -- White Riding Talbuk
				ground = 100,
			},
			[468] = { -- White Stallion
				ground = 60,
			},
			[16083] = { -- White Stallion
				ground = 100,
			},
			[34897] = { -- White War Talbuk
				ground = 100,
			},
			[54729] = { -- Winged Steed of the Ebon Blade
				flying = -1,
			},
			[581] = { -- Winter Wolf
				ground = 60,
			},
			[16081] = { -- Winter Wolf
				ground = 100,
			},
			[17229] = { -- Winterspring Frostsaber
				ground = 100,
			},
			[59791] = { -- Wooly Mammoth
				ground = 100,
			},
			[59793] = { -- Wooly Mammoth
				ground = 100,
			},
			[46197] = { -- X-51 Nether-Rocket
				flying = 60,
			},
			[46199] = { -- X-51 Nether-Rocket X-TREME
				flying = 280,
			},
			[26055] = { -- Yellow Qiraji Battle Tank
				ground = 100,
			},
			[48778] = { -- Acherus Deathcharger
				ground = 100,
			},
			[23214] = { -- Charger
				ground = 100,
			},
			[23161] = { -- Dreadsteed
				ground = 100,
			},
			[5784] = { -- Felsteed
				ground = 60,
			},
			[34767] = { -- Summon Charger
				ground = 100,
			},
			[34769] = { -- Summon Warhorse
				ground = 60,
			},
			[13819] = { -- Warhorse
				ground = 60,
			},
		},
		speeds = {
			flying = {
				[60] = false,
				[280] = true,
				[310] = true,
			},
			ground = {
				[0] = false,
				[60] = true,
				[100] = true,
			},
			swimming = {
				[60] = true,
			},
		},
	},
}

-- Generated on Sun, 17 May 2009 10:16:00 -0700 in 57.443286895752 seconds
