-- this file was automatically generated by wowhead.php

local Doolittle = LibStub("AceAddon-3.0"):GetAddon("Doolittle")

Doolittle.mounts = {
	pools = {
		flying280 = Pool{
			60025, -- Albino Drake
			63844, -- Argent Hippogryph
			61230, -- Armored Blue Wind Rider
			61229, -- Armored Snowy Gryphon
			59567, -- Azure Drake
			41514, -- Azure Netherwing Drake
			62048, -- Black Dragonhawk Mount
			59650, -- Black Drake
			61996, -- Blue Dragonhawk
			59568, -- Blue Drake
			59996, -- Blue Proto-Drake
			39803, -- Blue Riding Nether Ray
			59569, -- Bronze Drake
			43927, -- Cenarion War Hippogryph
			41515, -- Cobalt Netherwing Drake
			43810, -- Frost Wyrm
			51960, -- Frostwyrm Mount
			61294, -- Green Proto-Drake
			39798, -- Green Riding Nether Ray
			48025, -- Headless Horseman's Mount
			41513, -- Onyx Netherwing Drake
			41516, -- Purple Netherwing Drake
			39801, -- Purple Riding Nether Ray
			61997, -- Red Dragonhawk
			59570, -- Red Drake
			59961, -- Red Proto-Drake
			39800, -- Red Riding Nether Ray
			39802, -- Silver Riding Nether Ray
			32242, -- Swift Blue Gryphon
			32290, -- Swift Green Gryphon
			32295, -- Swift Green Wind Rider
			61442, -- Swift Mooncloth Carpet
			32292, -- Swift Purple Gryphon
			32297, -- Swift Purple Wind Rider
			32289, -- Swift Red Gryphon
			32246, -- Swift Red Wind Rider
			61444, -- Swift Shadoweave Carpet
			61446, -- Swift Spellfire Carpet
			32296, -- Swift Yellow Wind Rider
			60002, -- Time-Lost Proto-Drake
			44151, -- Turbo-Charged Flying Machine
			59571, -- Twilight Drake
			41517, -- Veridian Netherwing Drake
			41518, -- Violet Netherwing Drake
			54729, -- Winged Steed of the Ebon Blade
			46199, -- X-51 Nether-Rocket X-TREME
		},
		flying310 = Pool{
			40192, -- Ashes of Al'ar
			59976, -- Black Proto-Drake
			58615, -- Brutal Nether Drake
			64927, -- Deadly Gladiator's Frostwyrm
			63956, -- Ironbound Proto-Drake
			44317, -- Merciless Nether Drake
			44744, -- Merciless Nether Drake
			63796, -- Mimiron's Head
			3363, -- Nether Drake
			32345, -- Peep the Phoenix Mount
			60021, -- Plagued Proto-Drake
			63963, -- Rusted Proto-Drake
			37015, -- Swift Nether Drake
			49193, -- Vengeful Nether Drake
			60024, -- Violet Proto-Drake
		},
		flying60 = Pool{
			32244, -- Blue Wind Rider
			32239, -- Ebon Gryphon
			44153, -- Flying Machine
			32235, -- Golden Gryphon
			32245, -- Green Wind Rider
			48025, -- Headless Horseman's Mount
			32240, -- Snowy Gryphon
			32243, -- Tawny Wind Rider
			54729, -- Winged Steed of the Ebon Blade
			46197, -- X-51 Nether-Rocket
		},
		ground100 = Pool{
			43688, -- Amani War Bear
			16056, -- Ancient Frostsaber
			60114, -- Armored Brown Bear
			60116, -- Armored Brown Bear
			51412, -- Big Battle Bear
			58983, -- Big Blizzard Bear
			22719, -- Black Battlestrider
			16055, -- Black Nightsaber
			59572, -- Black Polar Bear
			26656, -- Black Qiraji Battle Tank
			17461, -- Black Ram
			60118, -- Black War Bear
			60119, -- Black War Bear
			48027, -- Black War Elekk
			22718, -- Black War Kodo
			59785, -- Black War Mammoth
			59788, -- Black War Mammoth
			22720, -- Black War Ram
			22721, -- Black War Raptor
			22717, -- Black War Steed
			22723, -- Black War Tiger
			22724, -- Black War Wolf
			25953, -- Blue Qiraji Battle Tank
			64656, -- Blue Skeletal Warhorse
			59573, -- Brown Polar Bear
			39315, -- Cobalt Riding Talbuk
			34896, -- Cobalt War Talbuk
			39316, -- Dark Riding Talbuk
			34790, -- Dark War Talbuk
			63635, -- Darkspear Raptor
			63637, -- Darnassian Nightsaber
			63639, -- Exodar Elekk
			36702, -- Fiery Warhorse
			63643, -- Forsaken Warhorse
			17460, -- Frost Ram
			23509, -- Frostwolf Howler
			63638, -- Gnomeregan Mechanostrider
			59810, -- Grand Black War Mammoth
			59811, -- Grand Black War Mammoth
			61465, -- Grand Black War Mammoth
			61467, -- Grand Black War Mammoth
			60136, -- Grand Caravan Mammoth
			60140, -- Grand Caravan Mammoth
			59802, -- Grand Ice Mammoth
			59804, -- Grand Ice Mammoth
			61469, -- Grand Ice Mammoth
			61470, -- Grand Ice Mammoth
			65637, -- Grea Red Elekk
			35713, -- Great Blue Elekk
			49379, -- Great Brewfest Kodo
			23249, -- Great Brown Kodo
			34407, -- Great Elite Elekk
			65641, -- Great Golden Kodo
			23248, -- Great Gray Kodo
			35712, -- Great Green Elekk
			35714, -- Great Purple Elekk
			23247, -- Great White Kodo
			18991, -- Green Kodo
			26056, -- Green Qiraji Battle Tank
			17465, -- Green Skeletal Warhorse
			48025, -- Headless Horseman's Mount
			59797, -- Ice Mammoth
			59799, -- Ice Mammoth
			17459, -- Icy Blue Mechanostrider Mod A
			63636, -- Ironforge Ram
			17450, -- Ivory Raptor
			66122, -- Magic Rooster
			66123, -- Magic Rooster
			66124, -- Magic Rooster
			61309, -- Magnificent Flying Carpet
			55531, -- Mechano-hog
			60424, -- Mekgineer's Chopper
			16084, -- Mottled Red Raptor
			29059, -- Naxxramas Deathcharger
			63640, -- Orgrimmar Wolf
			16082, -- Palomino
			23246, -- Purple Skeletal Warhorse
			41252, -- Raven Lord
			26054, -- Red Qiraji Battle Tank
			22722, -- Red Skeletal Warhorse
			579, -- Red Wolf
			16080, -- Red Wolf
			17481, -- Rivendare's Deathcharger
			39317, -- Silver Riding Talbuk
			34898, -- Silver War Talbuk
			63642, -- Silvermoon Hawkstrider
			23510, -- Stormpike Battle Charger
			63232, -- Stormwind Steed
			23241, -- Swift Blue Raptor
			43900, -- Swift Brewfest Ram
			23238, -- Swift Brown Ram
			23229, -- Swift Brown Steed
			23250, -- Swift Brown Wolf
			65646, -- Swift Burgundy Wolf
			23220, -- Swift Dawnsaber
			23221, -- Swift Frostsaber
			23239, -- Swift Gray Ram
			65640, -- Swift Gray Steed
			23252, -- Swift Gray Wolf
			35025, -- Swift Green Hawkstrider
			23225, -- Swift Green Mechanostrider
			23219, -- Swift Mistsaber
			65638, -- Swift Moonsaber
			23242, -- Swift Olive Raptor
			23243, -- Swift Orange Raptor
			23227, -- Swift Palomino
			33660, -- Swift Pink Hawkstrider
			35027, -- Swift Purple Hawkstrider
			65644, -- Swift Purple Raptor
			24242, -- Swift Razzashi Raptor
			65639, -- Swift Red Hawkstrider
			42777, -- Swift Spectral Tiger
			23338, -- Swift Stormsaber
			23251, -- Swift Timber Wolf
			65643, -- Swift Violet Ram
			47037, -- Swift War  Elekk
			35028, -- Swift Warstrider
			46628, -- Swift White Hawkstrider
			23223, -- Swift White Mechanostrider
			23240, -- Swift White Ram
			23228, -- Swift White Steed
			23222, -- Swift Yellow Mechanostrider
			48954, -- Swift Zhevra
			49322, -- Swift Zhevra
			24252, -- Swift Zulian Tiger
			39318, -- Tan Riding Talbuk
			34899, -- Tan War Talbuk
			18992, -- Teal Kodo
			63641, -- Thunder Bluff Kodo
			61425, -- Traveler's Tundra Mammoth
			61447, -- Traveler's Tundra Mammoth
			65642, -- Turbostrider
			64659, -- Venomhide Ravasaur
			15779, -- White Mechanostrider Mod B
			54753, -- White Polar Bear Mount
			39319, -- White Riding Talbuk
			65645, -- White Skeletal Warhorse
			16083, -- White Stallion
			34897, -- White War Talbuk
			16081, -- Winter Wolf
			17229, -- Winterspring Frostsaber
			59791, -- Wooly Mammoth
			59793, -- Wooly Mammoth
			26055, -- Yellow Qiraji Battle Tank
			48778, -- Acherus Deathcharger
			23214, -- Charger
			23161, -- Dreadsteed
			34767, -- Summon Charger
		},
		ground60 = Pool{
			58983, -- Big Blizzard Bear
			35022, -- Black Hawkstrider
			6896, -- Black Ram
			64977, -- Black Skeletal Horse
			470, -- Black Stallion
			578, -- Black Wolf
			64658, -- Black Wolf
			35020, -- Blue Hawkstrider
			10969, -- Blue Mechanostrider
			33630, -- Blue Mechanostrider
			6897, -- Blue Ram
			17463, -- Blue Skeletal Horse
			50869, -- Brewfest Kodo
			43899, -- Brewfest Ram
			50870, -- Brewfest Ram
			49378, -- Brewfest Riding Kodo
			34406, -- Brown Elekk
			458, -- Brown Horse
			18990, -- Brown Kodo
			6899, -- Brown Ram
			17464, -- Brown Skeletal Horse
			6654, -- Brown Wolf
			6648, -- Chestnut Mare
			6653, -- Dire Wolf
			8395, -- Emerald Raptor
			17458, -- Fluorescent Green Mechanostrider
			61451, -- Flying Carpet
			16060, -- Golden Sabercat
			35710, -- Gray Elekk
			18989, -- Gray Kodo
			6777, -- Gray Ram
			459, -- Gray Wolf
			15780, -- Green Mechanostrider
			17453, -- Green Mechanostrider
			48025, -- Headless Horseman's Mount
			10795, -- Ivory Raptor
			10798, -- Obsidian Raptor
			471, -- Palamino
			472, -- Pinto
			16058, -- Primal Leopard
			35711, -- Purple Elekk
			35018, -- Purple Hawkstrider
			17455, -- Purple Mechanostrider
			17456, -- Red and Blue Mechanostrider
			34795, -- Red Hawkstrider
			10873, -- Red Mechanostrider
			17462, -- Red Skeletal Horse
			18363, -- Riding Kodo
			8980, -- Skeletal Horse
			42776, -- Spectral Tiger
			10789, -- Spotted Frostsaber
			15781, -- Steel Mechanostrider
			8394, -- Striped Frostsaber
			10793, -- Striped Nightsaber
			16059, -- Tawny Sabercat
			580, -- Timber Wolf
			10796, -- Turquoise Raptor
			17454, -- Unpainted Mechanostrider
			10799, -- Violet Raptor
			64657, -- White Kodo
			6898, -- White Ram
			468, -- White Stallion
			581, -- Winter Wolf
			5784, -- Felsteed
			34769, -- Summon Warhorse
			13819, -- Warhorse
		},
		ground0 = Pool{
			30174, -- Riding Turtle
		},
		swimming60 = Pool{
			64731, -- Sea Turtle
		},
	},
	speeds = {
		flying = {
			[60] = false,
			[280] = true,
			[310] = true,
		},
		ground = {
			[0] = false,
			[60] = true,
			[100] = true,
		},
		swimming = {
			[60] = true,
		},
	},
}

-- Generated on Sun, 31 May 2009 13:58:18 -0700 in 78.652590036392 seconds
